###
### create account
POST http://localhost:8088/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 10000
}

### delete account
DELETE http://localhost:8088/account
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1000000000"
}

### get account
GET http://localhost:8088/account?user_id=1
Accept: application/json